algebra
=======

* <<ssm,signatures, structures, models>>
* <<monoid,example: monoid>>
* <<api,api>>
* <<impl,implementation>>
* <<algebras,some algebras>>

= [[ssm]] signatures, structures, models

Roughly speaking, and algebra is a set of symbols mapped to a set of
semantic values, plus a set of rules governing the behavior or the
symbols.  Wikipedia says "In mathematics, and more specifically in
abstract algebra, the term algebraic structure generally refers to a
set (called carrier set or underlying set) with one or more finitary
operations defined on it that satisfies a some list of axioms."
(link:https://en.wikipedia.org/wiki/Algebraic_structure[Algebraic
Structure]).

There are a variety of ways to think about the idea of an algebra more
formally.  For example, in
link:https://en.wikipedia.org/wiki/Universal_algebra[Universal
Algebra] an algebra (or algebraic structure) is "a set A together with
a collection of operations on A."  This view corresponds to the notion
of algebraic structure expressed above; notice that under this view
what matters is the mathematical structure: a set with operations,
without regard to the language we use to talk about such structures.
A different view comes from both logic and
link:https://en.wikipedia.org/wiki/Model_theory[Model Theory], which
make an explicit distinction between the symbol set (or
link:https://en.wikipedia.org/wiki/Signature_(logic)[signature]) of an
algebra and its carrier set.

The model-theoretic perspective is more finely articulated, in that it
distinguishes between distinct components of an algebra:

* a link:Signatures.adoc[signature], which is a set of symbols of different arities

* a set of _axioms_ (rules) governing the formal behavior (but _not_
  the meaning) of the symbols

* a link:Structures.adoc[structure], which is an abstract mathematical collection of
  values and functions on those values

* a link:Models.adoc[model], which is a mapping from the signature to the structure
  under which the axioms come out as true

Note that a signature is a purely formal _linguistic_ device, and
therefore devoid of meaning, while a structure is a purely informal
_extra-linguistic_ device, and therefore devoid of expressibility.
Signatures only become meaningful, and structures expressible, _under
a model_; that is, when we have agreed on a mapping from the one to
the other.  Models (more generally, interpretations) allow us to use
formal symbols to refer to informal mathematical values.

There is a subtlety here that is easy to miss: "'symbols' can be any
mathematical objects, not necessarily written symbols."
(link:https://books.google.com/books/about/A_Shorter_Model_Theory.html?id=S6QYeuo4p1EC[Hodges,
_A Shorter Model Theory]) So we can take an abstract view on the
notion of a signature, and this means that we can express the same
algebraic structure using different concrete symbols.  For example, we
could choose the standard numerals {0..9} for an algebra, or we could
use an alphabetic symbol set {a,b,c,d,e,f,g,h,i,j} instead - in fact
we could use any set of ten distinct symbols.  Structurally and
semantically everything would come out the same; they would just look
different.

This suggests a need to distinguish between abstract and concrete
signatures, just as we distinguish between abstract and concrete
structures (e.g. sequence v. sequence of integers).

For example, we might specify an algebraic signature abstractly by
saying it consists of three constant symbols and one binary operation
symbol.  We might make this more concrete by specifying {0,1,2,+}, or
{a,b,c,!}, or any other collection of four concrete symbols.

Here another subtlety arises.  Actually two subtleties: one the one
hand we need to distinguish between the _constant_ symbols of the
signature, and the _variable_ symbols we will want to use in order to
express the idea of "some (unknown) value"; and on the other, we need
to think about the categorization of the constant symbols and the
"values" (structures) they are intended to represent.  Informally, we
tend to make a distinction between, say, integers and functions.  But
if we closely analyse these concepts we quickly run into trouble; it's
difficult to say exactly what an integer _is_, for example.  From the
perspective of Set Theory, there is no essential difference between an
integer and a function, for example; both are sets.  They may have
different structure, but in the end they're just sets.

To avoid polluting our conceptual space with lots of philosophical and
meta-mathematical/logical complications, we can simply declare that
all symbols in our signature have an _arity_, including the "constant"
symbols like 1,2,3 etc.  We just treat such symbols as having arity
zero.  Which means that we treat all our symbols as function symbols,
which also implies that we should think of our structures also in
functional terms.

=== [[monoid]] an example: monoid

A (the?) monoid abstract signature is a set of symbols.  One nullary
symbol is designated as the identity symbol, and one binary symbol is
designated as the multiplication symbol.  There are three axioms:

* closure: any two symbols combined by the multiplication symbol form another symbol in the set

* identity: any symbol multiplied by the identity symbol produces the original symbol

* associativity: when multiplying three symbols, ....

Trying to express associativity in abstract language, without using
symbols, is a pain.  It's easier to settle on a few _meta-symbols_ and
variable symbols that allow us to express axioms clearly and concisely
by writing down _equations_.  It's critical to understand that these
(necessarily concrete) symbols are not part of the abstract symbol
set; their sole purpose is to state rules _about_ the abstract symbols
and their combination:

* variable symbols: a, b, c
* identity symbol: e
* binary function symbol: *
* equality symbol: =
* axiom of closure:  for all a, b in the symbol set, a*b is in the symbol set
* axiom of identity: for all a in the symbol set, a*e = e*a = a
* axiom of associativity:  for all a, b, c in the symbol set, a*(b*c) = (a*b)*c

Again, it's critically important to see that these symbols are not
part of the algebra's symbol set, abstract or concrete.  They're
meta-symbols that we use to talk _about_ the abstract symbol set.

Having defined the monoid algebra abstractly, we can declare a
concrete signature for the algebra:

* let the symbol set be the base set {0..9} together with the
  syntactic rules for positional notation that make e.g. "27" a symbol
  of the set, plus the symbol '+'.

* let the identity element 'e' map to symbol '0'

* let the binary function '*' map to symbol '+'

* let the equality meta-symbol and the variable symbols play the same
  roles in the concrete signature

That's it.  The abstract axioms will apply to this concrete symbol set
without modification, since they are expressed abstractly and we have
provided a concrete interpretation.

This allows us to write expressions like 2*3 or 3*e, which translate
to 2+3 and 3+0 respectively.

That gives us syntax, but we still have no semantics.  The symbols and
expressions remain purely formal.  To remedy this we need to define a
_model_ that maps the symbols of the signature to a _structure_ that
represents a _semantic domain_:

* let the constant symbols have the obvious "intended interpretation"
  e.g.  '=' => =, '+' => +, '0' => 0, '1' => 1, etc.

* let the variable set range across the integers

And we're done.  Now expressions like 2*3 mean something: 2*3 = 5
(remember we mapped '*' to '\+', and '+' to addition on Nat.)

= [[api]] api

Our "API" mimics the description for monoid construction given above:

* define an "algebra" - meaning, assume an unspecified abstract symbol
  set, and state the axioms and the distinguished elements using
  metasymbols and variables

* declare a signature for the algebra - nominate a concrete symbol
  set, and map the distinguished elements of the abstract signature to
  concrete symbols (e.g. map "e", the abstract identity symbol, to
  "0", an element of the concrete symbol set.

* declare a model for the signature of the algebra - specify the
  _implementation_ carrier set (as opposed to the _semantic_ carrier
  set, which is a mathematical abstraction); map the distinguished
  elements and operation symbols to implementation values and
  functions

* use the model to institute an environment and evaluate expressions "in the algebra"

Example:

[source,clojure]
----
(s/declare-algebra! a.b/Magma
                    "I am the magma docstring"
                    ;; :constants #{}  ;; no distinguished elements in a magma
                    :operators [(* [a b] "magma binop")]
                    :laws {:closure f}) ;; fn f expresses axiom of closure

(s/declare-algebra! a.b/Monoid
                    "I am the monoid docstring"
		    :expand [a.b/Magma] ;; "inheritance", but not really
                    :constants #{:e}
                    :laws {:identity #(= (* % e) %)
                           :associativity (fn [a b c] (= (* a (* b c)) (* (* a b) c))) })
----

Here `:expand` says that Monoid is an _expansion_ of Magma, meaning
Monoid includes the constants, operators, and laws of Magma.

Now _declare_ (not define!) a concrete signature for the abstract algebra:

[source,clojure]
----
;; additive monoid on Nat+
(s/declare-signature! a.b.sig/MonoidN0+ :for a.b/Monoid
                      :symbol-set :Nat
                      :constants {:e 0}
                      :operators {:* +})

;; multiplicative monoid on Nat
(s/declare-signature! a.b.sig/MonoidN1* :for a.b/Monoid
                      :symbol-set :Nat+
                      :constants {:e 1}
                      :operators {:* *})
----

We still only have formal signatures.  To provide semantics we _define_ models:

[source,clojure]
----
(s/declare-model! a.b.model/MonN0+ :for a.b.sig/MonoidN0+
  :universe {:sym :Nat ;; this is an implementation of :Nat declared in a.b.sig/MonoidN0+
             :impl {:type java.lang.Long ; implementation type
                    :restriction #(> % -1)}}  ; to be used for type-checking
  :constants {:e 0}
  :operators {:* +})

(s/declare-model! a.b.model/MonN1* :for a.b.sig/MonoidN1+
  :universe {:sym :Nat+
             :impl {:type java.lang.Long ; implementation type
                    :restriction pos?}}  ; to be used for type-checking
  :constants {:e 1}
  :operators {:* *})
----

Now we're ready to compute:

[source,clojure]
----
 (s/with-model a.b.model/MonN0+ ;; :for a.b.sig/MonoidN0+ - just an informative annotation
   e       ; => 0
   (* 3 e) ; => 3
   (* 3 5)) ; => 8

 (s/with-model a.b.model/MonN1* ;; :for a.b.sig/MonoidN1*
   e       ; => 1
   (* 3 e) ; => 3
   (* 3 5)) ; => 15
----


= [[impl]] implementations

link:Implementations.adoc[implementations]


= [[algebras]] some algebras

=== link:https://en.wikipedia.org/wiki/Magma_(algebra)[magma]

"a set, M, equipped with a single binary operation, M × M → M. The binary operation must be closed by definition but no other properties are imposed."

"For all a, b in M, the result of the operation a • b is also in M." (link:https://en.wikipedia.org/wiki/Magma_(algebra)#Definition[magma])

Example:  Cayley table (link:http://math.stackexchange.com/questions/779507/can-you-give-me-some-concrete-examples-of-magmas[])

link:http://arxiv.org/ftp/math/papers/0304/0304490.pdf[]


=== link:https://en.wikipedia.org/wiki/Semigroup[semigroup]

set with associative binary combinator; an associative magma

link:https://en.wikipedia.org/wiki/Semigroup#Definition[definition]: "A semigroup is a set S together with a binary operation "\cdot" (that is, a function \cdot:S\times S\rightarrow S) that satisfies the associative property"

=== link:https://en.wikipedia.org/wiki/Monoid[monoid]

semigroup with identity

==== link:https://en.wikipedia.org/wiki/Free_monoid[free monoid]

=== link:https://en.wikipedia.org/wiki/Group_(mathematics)[group]

monoid with inverse

==== link:https://en.wikipedia.org/wiki/Abelian_group[Abelian group]

closure, associativity, identity, inverses, commutativity

==== link:https://en.wikipedia.org/wiki/Symmetric_group[symmetric group]

==== link:https://en.wikipedia.org/wiki/Quotient_group[quotient group]

=== link:https://en.wikipedia.org/wiki/Ring_(mathematics)[Ring]

Two ops, addition and multiplication; abelian group under addition,
monoid under multiplication; multiplication is distributive w/r/t
addition.

=== link:https://en.wikipedia.org/wiki/Field_(mathematics)[Field]

Ring where multiplication is also commutative - both + and * are abelian

=== link:https://en.wikipedia.org/wiki/Vector_space#Definition[Vector Space]
